# this is redis config file
[list]
    [list.default]
        proxy_list = ["192.168.0.184:7379"]
        conn_timeout = 500
        password = "cKdHKdXl"
        db = 0
        read_timeout = 1000
        write_timeout = 1000
        max_active = 200
        max_idle = 500